### ISSUE TITLE
How should i do this step

### ISSUE THREAD

**Issue by KongDeyu1532** [Hassassistant/openai_response#13]
How should i do this step：To generate a response from GPT-3, update the input_text.gpt_input entity with the text you want to send to the model. The generated response will be available as an attribute of the sensor.hassio_openai_response entity.

**Comment by dnikles** [comment]
> How should i do this step：To generate a response from GPT-3, update the input_text.gpt_input entity with the text you want to send to the model. The generated response will be available as an attribute of the sensor.hassio_openai_response entity.

service: input_text.set_value

**Comment by IamTheLoki** [comment]
Hello, can some one plz get an example how i do that integrated that to my UI?
If I use the example the GPT respons is always empty. If I Use the Integration as an assist i get a response.

```
square: false
type: grid
columns: 1
cards:
  - type: entities
    entities:
      - entity: input_text.gpt_input
    title: Chat GPT Input
  - type: markdown
    content: '{{ state_attr(''sensor.hassio_openai_response'', ''response_text'') }}'
    title: Chat GPT Response

```
