### ISSUE TITLE
Using it as Assist?

### ISSUE THREAD

**Issue by Sturmkater** [Hassassistant/openai_response#17]
Hi, thank you for your work!
Is it somehow possible to use your adon as an assist? That way I could use ChatGPT as an assistant on my phone via Home Assistant.

**Comment by andrejsoucek** [comment]
@Sturmkater 
configuration.yaml:
```
intent_script:
  ChatGPT:
    action:
      - service: input_text.set_value
        data:
          value: "{{ prompt }}? Answer in one sentence."
        target:
          entity_id: input_text.gpt_input
      - delay: "00:00:02" # it takes some time to get the response
    speech:
      text: >
          {{ state_attr('sensor.hassio_openai_response', 'response_text') }}
```
custom_sentences/xx/chatgpt.yaml:
```
language: "xx"
intents:
  ChatGPT:
    data:
      - sentences:
          - "ask the prophecy {prompt}"
lists:
  prompt:
    wildcard: true
```
@Hassassistant might be worth adding this to readme

However there needs to be the delay in the script to wait for the response. I think this addon could be re-done to work as a callable service or script. Then we would just call the script and wait for the response.

**Comment by Deniz66** [comment]
What is wrong here? My response is empty

```
alias: GPT
description: ""
trigger: []
condition: []
action:
  - service: input_text.set_value
    target:
      entity_id: input_text.gpt_input
    data:
      value: "Test Message "
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - device_id: 5b61253e56eae41f958bfa6378bbe3d5
    domain: mobile_app
    type: notify
    message: "{{ state_attr('sensor.hassio_openai_response', 'response_text') }}"
    title: Postkasten
mode: single

```
