### ISSUE TITLE
probably a dumb question, how do i create the Create an input_text.gpt_input entity ?

### ISSUE THREAD

**Issue by twist3dimages** [Hassassistant/openai_response#9]
I am sort of new to Home Assistant and was wondering how I do this part

Create an input_text.gpt_input entity in Home Assistant to serve as the input for the GPT-3 model. 

thank you!

**Comment by Hassassistant** [comment]
add this to your configuration.yaml
else you can create an input text on the helpers page.

```
input_text:
  gpt_prompt:
    initial: ""
    max: 255
```
